require "config.autopairs"
require "config.cmp"
require "config.colorscheme"
require "config.diagnostics"
require "config.git"
require "config.keymaps"
require "config.line"
-- require "config.llm"
require "config.lsp"
require "config.options"
require "config.tabs"
require "config.telescope"
require "config.tree"
require "config.treesitter"
require "config.whichkey"
require "config.markdown"
